# Generated by Django 3.2.7 on 2021-10-08 15:59

import authentification.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_auto_20211007_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=authentification.models.get_file_path, verbose_name='Аватарка'),
        ),
    ]
